version: "3.5"

volumes:
  postgres-data:
  ipfs-data:

services:
  

  graph-node:
    image: patelnitish/graph-node
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2Gb
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: postgres_pass
      postgres_db: graph-node
      ipfs: "ipfs:5001"
      ethereum: "apothem:https://erpc.apothem.network/"
      GRAPH_LOG: debug
      ETHEREUM_POLLING_INTERVAL: 5000
      ETHEREUM_ANCESTOR_COUNT: 4
      ETHEREUM_REORG_THRESHOLD: 4
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'
    volumes:
      - ipfs-data:/data/ipfs
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: graph-node
    volumes:
      - postgres-data:/var/lib/postgresql/data
